<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Deformation.Abstractions\Deformation.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNet" Version="4.1.0" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
  </ItemGroup>

</Project>
