<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Page Include="App.xaml" />
		<ApplicationDefinition Remove="App.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\app.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Visualization.Rendering\Visualization.Rendering.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\Icons\app.ico" />
	</ItemGroup>

</Project>