<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\app.ico" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Deformation.IO\Deformation.IO.csproj" />
	  <ProjectReference Include="..\Deformation.Interaction\Deformation.Interaction.csproj" />
	  <ProjectReference Include="..\Rendering.OpenGL\Rendering.OpenGL.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\Icons\app.ico" />
	</ItemGroup>

</Project>